# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddf1a3fbe52fb724769851caaa17e0251421cac9874e47076b80698f7980d7a170bf18bc348ed6ba5cf4084ce4bb2d447a40b2ca049fde96bfe2b8a1ecbcf7aa

test:
  secret_key_base: 22e4d1800bdbdcaf2f4204361a370450c3b42e692afb6cebfbb9590c796058194dc47061d50402b1ee5a8409abb8c21ce9f3da68ccc33e94dc650796e5197314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
